version: '3.8'

#networks:
#  internalnetwork:
#    driver: bridge

networks:
  internalnetwork:
    external: true


services:
  custservice:
    container_name: CustContainer-custservice
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    networks:
      - internalnetwork
    ports:
      - "8980:8980" # Updated to match server.port in application.properties

  stubservice:
    container_name: CustContainer-stubservice
    build:
      context: ./CustomerStubService
      dockerfile: Dockerfile
    networks:
      - internalnetwork
    ports:
      - "8981:8981" # Updated to match server.port in application.properties
